### ISSUE TITLE
Unprocessed log entries should be kept

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-coralogix-feeder#16]
From time to time, log entries are not accepted by coralogix (either connection reset or malformed). If this happens, log entries should be stored in a DLQ.

**Comment by tripodsan** [comment]
if it's only a connection issue, they should probably be rejected, so the next time they will be retried?

**Comment by dominique-pfister** [comment]
not sure, whether a subscription filter has the same reject-retry semantics as an SQS induced trigger, but I'll check
